version: '2'
services:
  attacker:
    build: .
    hostname: attacker
    command: /usr/sbin/init
    networks:
      vpcbr:
        ipv4_address: 10.0.0.2

  victim:
    build: .
    hostname: victim
    command: /usr/sbin/init
    networks:
      vpcbr:
        ipv4_address: 10.0.0.3

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/8

